# Generated by Django 4.2.4 on 2023-11-24 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigu', models.CharField(max_length=255)),
                ('average_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_money', models.IntegerField()),
                ('saving_money', models.IntegerField()),
                ('total_money', models.IntegerField()),
                ('target_place', models.TextField()),
                ('move_time', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
